---
title: "data descriptive"
author: "Xiaoyang Li"
date: "2019/12/6"
output: html_document
---
```{r}
library(tidyverse)
library(patchwork)
library(arsenal)
```


## data cleaning
```{r}
lawsuit = read.csv("./data/Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
  dept = factor(dept, levels = c("1","2","3","4","5","6"),
         labels = c("Biochemistry/Molecular Biology","Physiology","Genetics","Pediatrics","Medicine","Surgery")
         ),
  gender = factor(gender, levels = c("1","0"),
                  labels = c("Male","Female")),
  clin  = factor(clin, levels = c("1","0"),
                 labels = c("Primarily clinical emphasis","Primarily research emphasis")),
  cert = factor(cert,levels = c("1","0"),
                labels = c("Board certified","not certified")),
  rank = factor(rank, levels = c("1","2","3"),
                labels = c("Assistant","Associate","Full professor"))
  )
```

## descriptive

```{r}

my_controls <- tableby.control(
  test = T,
  total = T,
  numeric.test = "kwt", cat.test = "chisq",
  numeric.stats = c("meansd", "medianq1q3", "range", "Nmiss2"),
  cat.stats = c("countpct", "Nmiss2"),
  stats.labels = list(
    meansd = "Mean (SD)",
    medianq1q3 = "Median (Q1, Q3)",
    range = "Min - Max",
    Nmiss2 = "Missing"
  )
)
 
my_labels <- list(
  dept = "Department",
  clin = "Clinical Emphasis",
  cert = "Certification",
  prate = "Publication Rate",
  exper = "Experience",
  rank = "Rank",
  sal94 = "Salary in 1994",
  sal95 = "Salary after Increment"
)

 
table_two <- tableby(gender ~ .,
  data = lawsuit,
  control = my_controls
)
 
summary(table_two,
  labelTranslations = my_labels,
  title = "Summary Statistic of lawsuit Data",
  pfootnote = TRUE,text = FALSE
)

lawsuit1 = lawsuit %>% 
  group_by(gender) %>% 
  mutate(
    mean_prate = mean(prate),
    mean_exper = mean(exper),
    mean_sal94 = mean(sal94),
    mean_sal95 = mean(sal95)
  )

dept_plot = ggplot(lawsuit, aes(x = dept)) +
  geom_bar(aes(fill = gender))+
   theme(axis.text.x = element_text(vjust = 0.5, hjust = 0.5, angle = 90))+ theme(legend.position = "top")
           
clin_plot = ggplot(lawsuit, aes(x = clin))+
  geom_bar(aes(fill = gender))+
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 0.5, angle = 90))+ theme(legend.position = "top")

cert_plot = ggplot(lawsuit, aes(x = cert))+
  geom_bar(aes(fill = gender))+
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 0.5, angle = 90))+ theme(legend.position = "top")

prate_plot = ggplot(lawsuit, aes(x = prate))+
  geom_density(aes(fill= gender,y = ..count..),alpha = 0.4)+
   geom_vline(aes(xintercept = mean_prate, color = gender),
             data = lawsuit1, linetype = "dashed")

rank_plot = ggplot(lawsuit, aes(x = rank)) +
  geom_bar(aes(fill = gender)) +
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 0.5, angle = 90)) + theme(legend.position = "top")

sal94_plot = ggplot(lawsuit1, aes(x = sal94)) +
  geom_density(aes(fill = gender, y = ..count..), alpha = 0.4) +
  geom_vline(aes(xintercept = mean_sal94, color = gender),
             data = lawsuit1, linetype = "dashed")

sal95_plot = ggplot(lawsuit1, aes(x = sal95)) +
  geom_density(aes(fill = gender, y = ..count..), alpha = 0.4) +
  geom_vline(aes(xintercept = mean_sal95, color = gender),
             data = lawsuit1, linetype = "dashed")

(dept_plot | clin_plot | cert_plot | rank_plot ) / (prate_plot  + sal94_plot + sal95_plot)
```

