---
title: "introduction"
author: "Jingyu Fu"
date: "2019/12/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Introduction

Gender inequality has always been a hotspot in society. Studies have shown gender inequalities in multiple fields, including economic participation and opportunity, educational attainment, health and survival, political empowerment^[1]. Among those four, gender gap in salary reveals the one of deepest social inequalities and hence is of greatest concern. 

Gender gap in salary is discovered in various fields, including political, educational and economical fields. The overall result is that female has 20% less the salary compared to the male^[2]. However, it is less commonly talked about that the gender gap also exists in payment of doctors. Doctors are believed to be one of the most high class careers in the world, and hence it is intuitively believed that there should be less gender inequality of salary in doctors. In fact, unlike our intuitive, male doctors earn 20% more salary than female in pediatric emergency nationwide^[3]. This inequality is partially dismissed by the fact that male and female doctors are in different professional fields, therefore the study of gender gap in salary within more specific medical fields is heavily lacking. 

To address this problem, our study focuses on finding association between gender and salary to see if there really exists an inequality in gender. Considering that gender gap could vary from field to field, we took different subfields in the overall medical field, such as Biochemistry, Physiology and Genetics, as our variables. Moreover, to specify the effect of gender inequality and divide it from the effect of each person’s professional ability on salary, we added variables such as publication rates and career rank to our association study. 

References:

[1] The Global Gender Gap Report 2018.  world economic forum.   2018

[2] The global rage report 2018.  international labor organization.  2018

[3] Female doctors in Houston earn much less than men in same job. Jenny Deam. Huston Chronical.  April26, 2017 

## DISCUSSION

STUDY STRENGTHS. Our study strengths are mostly revealed by the variables we chose to meet our study needs. Since our study focused on gender bias in doctors’ payments, the main strength is that we specified various medical fields by including a variable that indicates biochemistry/molecular biology, physiology, genetics, pediatrics, medicine and surgery. In previous studies, gender gap in medical fields was less talked about because many took this gap as inherent difference within the medical fields. But with this variable we could tell that how gender gap is displayed in each field and which field is most seriously biased. In addition, we used a set of variables to represent differences in each person’s professional background regardless of gender. By adjusting our model we largely increased the comparability between distributions of causes other than gender that are associated with payment difference, hence the implication of gender on payment can be better revealed. 

STUDY LIMITATIONS. First, we did not have information about the profits of hospital each invested person works at. The overall profits of hospital may affect how it allocates salary to its doctors. Second, another potential cause of sally difference is location of the hospital. On the one hand, people living and working at different locations may have different medical needs, and doctors in the most needed medical field has a probability of gaining higher salaries. On the other hand, hospitals at different locations may have different levels of competitions, and a more fierce competition may lead to a lower salary of doctors. Third, we have the measure of years since obtaining MD, but this does not indicate the years doctors spent in a certain field. In fact, working experience in a field unrelated to the one from which they gained their salaries has a weak effect on the salary we obtained in our data. Finally, family status is also a potential cause with respect to salary gap. Doctors with a family may have a stronger motivation of gaining higher salary and hence work harder than those without. 
