---
title: "diagnostic"
author: "Xiaoyang Li"
date: "2019/12/8"
output: html_document
---
```{r}
library(tidyverse)
library(arsenal)
library(HH)
library(olsrr)
library(broom)
library(formattable)
library(htmltools)
library(webshot)
```


Data import
```{r}
data = read_csv('./data/Lawsuit.csv') %>%
  janitor::clean_names() %>%
  mutate(
    gender = factor(gender, levels = c(0,1), labels = c("female","male")),
    clin = factor(clin, levels = c(0,1)),
    cert = factor(cert, levels = c(0,1)),
    rank = factor(rank, levels = c(1,2,3))
  )

data$ln_sal94 = log(data$sal94)
data$ln_sal95 = log(data$sal95)
data$salavg = (data$sal94 + data$sal95)/2
data$ln_salavg = log(data$salavg)


```


```{r}
reg13 = lm(ln_salavg ~ gender*exper + factor(dept) + clin + cert + rank, data = data)
summary(reg13)
```



Non-linear models
```{r scatter plot}

data %>% 
  ggplot(aes(x = exper, y = ln_salavg)) +
  geom_point() +
  geom_smooth()

data %>% 
  filter(gender == "male") %>% 
  ggplot(aes(x = exper, y = ln_salavg)) +
  geom_point() +
  geom_smooth()

data %>% 
  filter(gender == "female") %>% 
  ggplot(aes(x = exper, y = ln_salavg)) +
  geom_point() +
  geom_smooth()
```

The only continuous variable is `exper`. So I made scatter plot for `exper` and `ln_salavg`. There is non-linear relationship between `exper` and `ln_salavg`. 


```{r polynomial}
data_poly = data %>% 
  mutate(exper_pow2 = exper^2,
         exper_pow3 = exper^3,
         exper_pow4 = exper^4)

poly_exper = lm(ln_salavg ~ gender*exper + factor(dept) + clin + cert + rank + exper_pow2 + exper_pow3 + exper_pow4 , data = data_poly) 

summary(poly_exper)
```

I add its power 2, 3, 4 to our model to create polynomial model firstly. But the summary result show there is no association between higher order of `exper` and `ln_salavg`.

```{r piecewise}

```


Diagnostic
```{r}
par(mfrow = c(2,2))
plot(reg13)
ols_plot_resid_stud_fit(reg13)
ols_plot_resid_lev(reg13)
```
